openapi: 3.0.0
info:
  title: URL Shortener API
  description: API untuk memendekkan URL panjang menjadi URL pendek.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Server lokal
paths:
  /:shorten?:
    post:
      summary: Memendekkan URL
      tags: [URL Shortener]
      description: Menerima URL panjang dan mengembalikan URL pendek yang terpendek.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                originalUrl:
                  type: string
                  format: uri
                  example: https://www.example.com/some-long-url
              required:
                - originalUrl
      responses:
        "200":
          description: URL berhasil dipendekkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success
                  data:
                    type: string
                    format: uri
                    example: http://localhost:3000/abc123
        "400":
          description: Permintaan tidak valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: Invalid URL format
        "500":
          description: Terjadi kesalahan pada server
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: Internal server error
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: Error message
    SuccessResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: Success
        data:
          type: string
          format: uri
          example: http://localhost:3000/abc123
